import { StudioToolMeta } from '@/types/studio';

export const SITE_CONFIG = {
  name: 'KYNOVIQ AI',
  shortName: 'Kynoviq AI',
  tagline: 'Think Smarter. Create Faster.',
  description:
    'Kynoviq AI is an intelligent all-in-one AI platform where creators, students, developers, freelancers, startups and businesses can create, edit, code, and manage digital content from one place.',
  url: 'https://kynoviq-ai.vercel.app',
  ogImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
  founder: {
    name: 'Mohammad Hassan Raza',
    role: 'Founder & CEO of Kynoviq AI',
    avatarUrl: '',
    bio: 'Visionary product engineer & architect pioneering unified AI operating systems for the next generation of global creators, developers, and enterprises.',
    email: 'mdhassanraza0879@gmail.com',
    phone: '7307670879',
    socials: {
      github: 'https://github.com/mdhassanraza0879-sudo',
      linkedin: 'https://linkedin.com',
      twitter: 'https://twitter.com',
    },
  },
  links: {
    github: 'https://github.com/mdhassanraza0879-sudo/kynoviq-ai',
    docs: '/tools',
    privacy: '/privacy',
    terms: '/terms',
    refund: '/refund',
    aiPolicy: '/ai-policy',
    cookiePolicy: '/cookie-policy',
    contact: '/contact',
    about: '/about',
    founder: '/founder',
    pricing: '/pricing',
    templates: '/templates',
  },
};

export const STUDIO_TOOLS: StudioToolMeta[] = [
  {
    id: 'agent',
    name: 'AI Creative Agent',
    tagline: 'Autonomous Campaign & Multi-Step DAG Engine',
    description: 'Transform a single goal into complete cross-platform campaigns—scripts, video, voiceover, captions, thumbnails, and social variants automatically.',
    category: 'Core AI',
    icon: 'Sparkles',
    href: '/agent',
    badge: 'Flagship Core',
    creditCost: 25,
    featured: true,
  },
  {
    id: 'script',
    name: 'AI Idea & Script Studio',
    tagline: 'High-Converting Viral Video Scripts',
    description: 'Generate full YouTube, TikTok, and commercial scripts with scene breakdowns, visual prompts, voiceover text, and B-roll directions.',
    category: 'Core AI',
    icon: 'FileText',
    href: '/studio/script',
    badge: 'Popular',
    creditCost: 1,
    featured: true,
  },
  {
    id: 'video',
    name: 'AI Video Generator',
    tagline: 'Cinematic Text & Image-to-Video Engine',
    description: 'Generate stunning 1080p/4K video scenes across 9:16, 16:9, 1:1, and 4:5 ratios with camera motion and custom styles.',
    category: 'Video & Motion',
    icon: 'Video',
    href: '/studio/video',
    badge: 'Next-Gen',
    creditCost: 15,
    featured: true,
  },
  {
    id: 'editor',
    name: 'AI Browser Video Editor',
    tagline: 'Multi-Track Cloud Timeline & FX Studio',
    description: 'Trim, split, crop, animated text, audio mixing, AI captions, silence removal, and auto-shorts generator in your browser.',
    category: 'Video & Motion',
    icon: 'Film',
    href: '/studio/editor',
    badge: 'Studio Grade',
    creditCost: 5,
    featured: true,
  },
  {
    id: 'image',
    name: 'AI Image & Poster Generator',
    tagline: 'Photorealistic Visuals & Thumbnails',
    description: 'Text-to-image, background remover, object eraser, smart upscale, product mockups, and high-impact poster graphics.',
    category: 'Image & Visuals',
    icon: 'Image',
    href: '/studio/image',
    badge: 'Ultra 8K',
    creditCost: 2,
    featured: true,
  },
  {
    id: 'voiceover',
    name: 'AI Voiceover Studio',
    tagline: 'Studio-Grade Multilingual Neural Voices',
    description: 'Generate natural, human-like voiceovers in Hindi, English, and 30+ languages with emotional style and pitch controls.',
    category: 'Audio & Voice',
    icon: 'Mic',
    href: '/studio/voiceover',
    badge: 'Multilingual',
    creditCost: 3,
    featured: true,
  },
  {
    id: 'captions',
    name: 'Auto Captions & Subtitles',
    tagline: 'Dynamic Viral Captions & Word Timestamps',
    description: 'Automatically transcribe speech and overlay animated TikTok/Hormozi-style subtitle graphics with custom colors.',
    category: 'Video & Motion',
    icon: 'Captions',
    href: '/studio/captions',
    badge: 'Viral Hook',
    creditCost: 2,
  },
  {
    id: 'dubbing',
    name: 'AI Video Dubbing',
    tagline: 'Zero-Friction Multilingual Translation',
    description: 'Translate and dub existing videos into Hindi, English, Spanish, and more with voice cloning and audio sync.',
    category: 'Audio & Voice',
    icon: 'Languages',
    href: '/studio/dubbing',
    badge: 'Global Reach',
    creditCost: 10,
  },
  {
    id: 'music',
    name: 'AI Music & Sound Suggestions',
    tagline: 'Royalty-Free Soundtrack Matching',
    description: 'Smart mood-based music matching with BPM and key detection, 100% cleared for commercial YouTube and social media monetization.',
    category: 'Audio & Voice',
    icon: 'Music',
    href: '/studio/music',
    badge: 'Royalty Free',
    creditCost: 1,
  },
  {
    id: 'reels',
    name: 'Reels / Shorts Creator',
    tagline: '1-Click Viral Short-Form Factory',
    description: 'Detect viral moments in long videos, auto-crop to vertical 9:16, add bold captions, and generate viral hooks in seconds.',
    category: 'Marketing & Social',
    icon: 'Smartphone',
    href: '/studio/reels',
    badge: 'Viral Factory',
    creditCost: 8,
  },
  {
    id: 'ad-creative',
    name: 'AI Ad Creative Generator',
    tagline: 'High-Converting Performance Ads',
    description: 'Enter your product and target audience to generate multi-variant Meta, TikTok, and Google ad concepts, hooks, and storyboards.',
    category: 'Marketing & Social',
    icon: 'Target',
    href: '/studio/ad-creative',
    badge: 'Conversion Pro',
    creditCost: 4,
  },
  {
    id: 'social',
    name: 'Social Media AI Studio',
    tagline: 'Cross-Platform Caption & Hashtag Suite',
    description: 'Craft optimized posts, viral carousels, and hashtag strategies for Instagram, YouTube, LinkedIn, X, and TikTok.',
    category: 'Marketing & Social',
    icon: 'Share2',
    href: '/studio/social',
    badge: 'Omnichannel',
    creditCost: 1,
  },
  {
    id: 'brand-kit',
    name: 'AI Brand Kit',
    tagline: 'Unified Visual Identity & Tone Injection',
    description: 'Store your logo, color palette, custom fonts, and brand voice. Automatically injected into all generated visual assets.',
    category: 'Core AI',
    icon: 'Palette',
    href: '/brand-kit',
    badge: 'Brand Engine',
    creditCost: 0,
  },
  {
    id: 'templates',
    name: 'Template Marketplace',
    tagline: '500+ Creator-Ready SaaS & Video Blueprints',
    description: 'Browse, remix, and publish from a library of verified templates for Reels, YouTube, Ads, Business, and E-commerce.',
    category: 'Marketing & Social',
    icon: 'Layers',
    href: '/templates',
    badge: 'Remixable',
    creditCost: 0,
  },
];

export const PRICING_PLANS = [
  {
    tier: 'FREE',
    name: 'Starter Creator',
    description: 'Perfect for exploring the AI creative ecosystem and experimenting with initial projects.',
    monthlyPrice: 0,
    yearlyPrice: 0,
    creditsPerMonth: 100,
    maxProjects: 5,
    maxStorageMb: 1000,
    features: [
      '100 Free AI Credits on signup & every month',
      'Access to all 14 Creative Studios',
      'Standard 1080p Video Generation',
      'Browser Video Editor with multi-track timeline',
      'Hindi & English AI Voiceovers',
      'Community & Discord Support',
    ],
    ctaText: 'Start Free Forever',
    isPopular: false,
  },
  {
    tier: 'PRO',
    name: 'Pro Creator',
    description: 'Engineered for influencers, freelance editors, agencies, and high-frequency content creators.',
    monthlyPrice: 29,
    yearlyPrice: 290,
    creditsPerMonth: 1000,
    maxProjects: 50,
    maxStorageMb: 25000,
    features: [
      '1,000 AI Credits per month',
      'Full AI Creative Agent DAG Orchestration',
      'Ultra HD 4K Video Exports & 60fps',
      'AI Multilingual Dubbing & Lip Sync',
      '1 Brand Kit with Automatic Tone Injection',
      'Commercial Monetization License',
      'Priority Cloud Rendering Queue',
      'Direct YouTube & Social Export Presets',
    ],
    ctaText: 'Upgrade to Pro',
    isPopular: true,
  },
  {
    tier: 'BUSINESS',
    name: 'Agency & Team',
    description: 'For growing creative teams, production studios, and brands demanding scale and collaboration.',
    monthlyPrice: 79,
    yearlyPrice: 790,
    creditsPerMonth: 4000,
    maxProjects: 999,
    maxStorageMb: 100000,
    features: [
      '4,000 AI Credits per month',
      'Team Collaboration & Role Permissions (5 Seats)',
      'Unlimited Brand Kits & Asset Libraries',
      'Shared Workspaces & Version Timeline',
      'Advanced Content Performance Analytics',
      'Bulk Reel / Short Generation Factory',
      'Dedicated Customer Success Architect',
      'Custom API & Webhook Integrations',
    ],
    ctaText: 'Launch Business Suite',
    isPopular: false,
  },
];

export const CREDIT_PACKAGES = [
  { id: 'pack_100', credits: 100, price: 5, bonus: 0, name: 'Mini Pack' },
  { id: 'pack_500', credits: 500, price: 19, bonus: 50, name: 'Creator Pack', isPopular: true },
  { id: 'pack_2000', credits: 2000, price: 59, bonus: 300, name: 'Studio Pack' },
];

export const FAQ_ITEMS = [
  {
    question: 'What is Kynoviq AI and how does it differ from regular AI chatbots?',
    answer:
      'Kynoviq AI is a complete AI Creative Operating System. Rather than just returning text, it unifies script generation, multi-track video editing, photorealistic image creation, neural voiceovers, automated subtitles, and multilingual dubbing into connected, production-ready workflows.',
  },
  {
    question: 'How does the AI Creative Agent work?',
    answer:
      'The AI Creative Agent takes a high-level goal (e.g. "Launch a 30-second campaign for my apparel brand") and autonomously creates a 10-step DAG workflow covering strategy, scripts, visuals, video scenes, voiceover, captions, and ad variations. You can pause, edit, regenerate, or approve each step seamlessly.',
  },
  {
    question: 'How do AI credits work?',
    answer:
      'Every generation transparently uses credits based on computing intensity. For example, Script generation costs 1 credit, Voiceover costs 3 credits, and HD Video generation costs 15 credits. You start with 50 free credits every month and can top-up anytime.',
  },
  {
    question: 'Can I monetize content created on Kynoviq AI?',
    answer:
      'Yes! All content generated using Kynoviq AI comes with full commercial rights for YouTube, Meta Ads, TikTok, client deliverables, and broadcast monetization.',
  },
  {
    question: 'Does the browser video editor require high-end computer hardware?',
    answer:
      'No. Our browser-based editor uses GPU-accelerated cloud pipelines and WebGL canvas rendering, allowing smooth multi-track editing, trimming, filters, and exports on standard laptops, Macs, and PCs.',
  },
  {
    question: 'Which languages are supported for voiceover and dubbing?',
    answer:
      'We support Hindi, English (US, UK, India, Australia), Spanish, French, German, Japanese, Portuguese, and architecture for 30+ additional global languages with high-fidelity neural accents.',
  },
];
