import { AIToolConfig } from '@/types';

export const AI_TOOLS: AIToolConfig[] = [
  {
    id: 'chat',
    type: 'CHAT',
    name: 'AI Chat',
    description: 'Have natural conversations with AI, ask complex questions, and get intelligent real-time answers.',
    iconName: 'MessageSquare',
    href: '/chat',
    category: 'Productivity',
    badge: 'Popular',
    systemPrompt: `You are Kynoviq AI, an intelligent, concise, and helpful AI assistant. Provide insightful, accurate, and beautifully structured responses using Markdown formatting.`,
  },
  {
    id: 'summarizer',
    type: 'SUMMARIZER',
    name: 'Smart Summarizer',
    description: 'Convert long articles, notes, reports, and text into concise, high-impact key summaries.',
    iconName: 'FileText',
    href: '/tools/summarizer',
    category: 'Productivity',
    badge: 'Fast',
    systemPrompt: `You are Kynoviq Smart Summarizer. Your goal is to extract core insights, key takeaways, and structured outlines from user text cleanly.`,
  },
  {
    id: 'study',
    type: 'STUDY',
    name: 'Study Assistant',
    description: 'Master difficult concepts with clear explanations, real-world examples, key terms, and interactive quizzes.',
    iconName: 'GraduationCap',
    href: '/tools/study',
    category: 'Learning',
    badge: 'Interactive',
    systemPrompt: `You are Kynoviq Study Assistant. Breakdown complex topics into accessible learning modules: simplified explanation, key points, concrete examples, key terminology, and quiz questions.`,
  },
  {
    id: 'code',
    type: 'CODE',
    name: 'Code Assistant',
    description: 'Analyze code snippets, diagnose hidden bugs, optimize performance, and generate clean refactored solutions.',
    iconName: 'Code2',
    href: '/tools/code',
    category: 'Coding',
    badge: 'Dev Favorite',
    systemPrompt: `You are Kynoviq Code Assistant. Analyze code, detect potential syntax/logic bugs, provide optimization tips, and output refactored production-grade code.`,
  },
  {
    id: 'writing',
    type: 'WRITING',
    name: 'Writing Assistant',
    description: 'Elevate your content grammar, tone, clarity, structure, and professional appeal effortlessly.',
    iconName: 'PenTool',
    href: '/tools/writing',
    category: 'Writing',
    systemPrompt: `You are Kynoviq Writing Assistant. Enhance text grammar, tone, flow, and elegance according to specified user modes.`,
  },
  {
    id: 'ideas',
    type: 'IDEAS',
    name: 'Idea Generator',
    description: 'Brainstorm high-converting startup concepts, marketing angles, product features, and creative strategies.',
    iconName: 'Lightbulb',
    href: '/tools/ideas',
    category: 'Creation',
    badge: 'Creative',
    systemPrompt: `You are Kynoviq Idea Generator. Generate novel, structured, actionable, and scalable business, product, or content ideas with target audience and execution highlights.`,
  },
];
